name: version-package

on:
  push:
    branches:
      - stage

jobs:
  version:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      pull-requests: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git config --global user.email "git@alecvision.com"
      - run: git config --global user.name "Alec Helmturner"
      - run: npm run version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
